### ISSUE TITLE
Interactions

### ISSUE THREAD

**Issue by smotched** [captain-camel/CoreCharts#7]
Love the simplicity and design of the library, any chance we could add gestures/interactions (something like the stocks app) that way we can also add a modifier to remove the background graph and have a simple chart.

Might be best to rename `.style` to something like `.chartStyle`, could run into some conflicts there.

Great work so far!

**Comment by captain-camel** [comment]
Thank you for the feedback! Adding interaction is what I plan on working on next, not 100% sure how that will work with the combined charts but it shouldn’t be too hard to find a way. 

Wdym by a modifier to remove the background? How does that relate to interaction?

Also, just out of curiosity, how did you find this project? I haven’t advertised it or anything so I’m  wondering how you came across it.

**Comment by smotched** [comment]
I was thinking the same about the multichart gesture. If its too difficult to do both with a [circle indicator](https://i.imgur.com/s1zD4Xc.png), we can make the interaction indicator [just a line](https://i.imgur.com/celyFeC.png) and display the values for both charts at those points above the chart and maybe their difference.

Well if there are interactions you may not want to display the x and y values. You would leave it to the user to view whatever part of the chart by interacting with the chart

I don't remember honestly, I was searching around github an ran into it :)
